language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to run tests
install:
  - pip install -r source/requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install pylint
script:
  - python source/drivertester.py
  - pytest --cov=source/ 
  - pylint source/main.py
  - pylint source/driver.py
after_success: 
  - coveralls
