language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to run tests
install:
  - pip install -r source/requirements.txt
script:
  - python source/drivertester.py
  - python source/seleniumtest.py
  
after_success: "sbt coveralls"
