language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to run tests
install:
  - pip install -r source/requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install pylint
  - pip install coverage
script:
  - python source/drivertester.py
  - pylint source/main.py
  - pylint source/driver.py
  - pylint source/drivertester.py
  - coverage run source/drivertester.py
after_success: 
  - coveralls
